/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_p4api_WRAP_H_
#define SWIG_p4api_WRAP_H_

class SwigDirector_ClientUser : public ClientUser, public Swig::Director {

public:
    SwigDirector_ClientUser();
    virtual ~SwigDirector_ClientUser();
    virtual void InputData(StrBuf *strbuf, Error *e);
    virtual void HandleError(Error *err);
    virtual void Message(Error *err);
    virtual void OutputError(char const *errBuf);
    virtual void OutputInfo(char level, char const *data);
    virtual void OutputBinary(char const *data, int length);
    virtual void OutputText(char const *data, int length);
    virtual void OutputStat(StrDict *varList);
    virtual void Prompt(StrPtr const &msg, StrBuf &rsp, int noEcho, Error *e);
    virtual void ErrorPause(char *errBuf, Error *e);
    virtual void Edit(FileSys *f1, Error *e);
    virtual void Diff(FileSys *f1, FileSys *f2, int doPage, char *diffFlags, Error *e);
    virtual void Merge(FileSys *all_your_base, FileSys *leg1, FileSys *leg2, FileSys *result, Error *e);
    virtual int Resolve(ClientMerge *m, Error *e);
    virtual void Help(char const *const *help);
    virtual FileSys *File(FileSysType type);
    virtual void Finished();
    virtual void SetOutputCharset(int arg0);
    virtual void DisableTmpCleanup();
    virtual int OutputError(char *errBuf);
    virtual int OutputInfo(char level, char *data);
    virtual int OutputBinary(char *data, int length);
    virtual int OutputText(char *data, int length);
    virtual int Help(char *const *help);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(char *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(char, char *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *, int);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, int);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, void *, int, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)(char *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(void *, void *, int, char *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *, void *, void *, void *, void *);
    typedef int (SWIGSTDCALL* SWIG_Callback13_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(void *);
    typedef void * (SWIGSTDCALL* SWIG_Callback15_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback17_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback18_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback19_t)(char *);
    typedef int (SWIGSTDCALL* SWIG_Callback20_t)(char, char *);
    typedef int (SWIGSTDCALL* SWIG_Callback21_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackInputData, SWIG_Callback1_t callbackHandleError, SWIG_Callback2_t callbackMessage, SWIG_Callback3_t callbackOutputError, SWIG_Callback4_t callbackOutputInfo, SWIG_Callback5_t callbackOutputBinary, SWIG_Callback6_t callbackOutputText, SWIG_Callback7_t callbackOutputStat, SWIG_Callback8_t callbackPrompt, SWIG_Callback9_t callbackErrorPause, SWIG_Callback10_t callbackEdit__SWIG_0, SWIG_Callback11_t callbackDiff, SWIG_Callback12_t callbackMerge, SWIG_Callback13_t callbackResolve, SWIG_Callback14_t callbackHelp, SWIG_Callback15_t callbackFile, SWIG_Callback16_t callbackFinished, SWIG_Callback17_t callbackSetOutputCharset, SWIG_Callback18_t callbackDisableTmpCleanup, SWIG_Callback19_t callbackOutputError2, SWIG_Callback20_t callbackOutputInfo2, SWIG_Callback21_t callbackHelp2);

private:
    SWIG_Callback0_t swig_callbackInputData;
    SWIG_Callback1_t swig_callbackHandleError;
    SWIG_Callback2_t swig_callbackMessage;
    SWIG_Callback3_t swig_callbackOutputError;
    SWIG_Callback4_t swig_callbackOutputInfo;
    SWIG_Callback5_t swig_callbackOutputBinary;
    SWIG_Callback6_t swig_callbackOutputText;
    SWIG_Callback7_t swig_callbackOutputStat;
    SWIG_Callback8_t swig_callbackPrompt;
    SWIG_Callback9_t swig_callbackErrorPause;
    SWIG_Callback10_t swig_callbackEdit__SWIG_0;
    SWIG_Callback11_t swig_callbackDiff;
    SWIG_Callback12_t swig_callbackMerge;
    SWIG_Callback13_t swig_callbackResolve;
    SWIG_Callback14_t swig_callbackHelp;
    SWIG_Callback15_t swig_callbackFile;
    SWIG_Callback16_t swig_callbackFinished;
    SWIG_Callback17_t swig_callbackSetOutputCharset;
    SWIG_Callback18_t swig_callbackDisableTmpCleanup;
    SWIG_Callback19_t swig_callbackOutputError2;
    SWIG_Callback20_t swig_callbackOutputInfo2;
    SWIG_Callback21_t swig_callbackHelp2;
    void swig_init_callbacks();
};


#endif
