/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace P4API {

public enum ErrorSeverity {
  E_EMPTY = 0,
  E_INFO = 1,
  E_WARN = 2,
  E_FAILED = 3,
  E_FATAL = 4
}

}
