/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace P4API {

using System;
using System.Runtime.InteropServices;

public class ErrorId : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ErrorId(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ErrorId obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ErrorId() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        p4apiPINVOKE.delete_ErrorId(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public int code {
    set {
      p4apiPINVOKE.ErrorId_code_set(swigCPtr, value);
    } 
    get {
      int ret = p4apiPINVOKE.ErrorId_code_get(swigCPtr);
      return ret;
    } 
  }

  public string fmt {
    set {
      p4apiPINVOKE.ErrorId_fmt_set(swigCPtr, value);
    } 
    get {
      string ret = p4apiPINVOKE.ErrorId_fmt_get(swigCPtr);
      return ret;
    } 
  }

  public int SubCode() {
    int ret = p4apiPINVOKE.ErrorId_SubCode(swigCPtr);
    return ret;
  }

  public int Subsystem() {
    int ret = p4apiPINVOKE.ErrorId_Subsystem(swigCPtr);
    return ret;
  }

  public int Generic() {
    int ret = p4apiPINVOKE.ErrorId_Generic(swigCPtr);
    return ret;
  }

  public int ArgCount() {
    int ret = p4apiPINVOKE.ErrorId_ArgCount(swigCPtr);
    return ret;
  }

  public int Severity() {
    int ret = p4apiPINVOKE.ErrorId_Severity(swigCPtr);
    return ret;
  }

  public int UniqueCode() {
    int ret = p4apiPINVOKE.ErrorId_UniqueCode(swigCPtr);
    return ret;
  }

  public ErrorId() : this(p4apiPINVOKE.new_ErrorId(), true) {
  }

}

}
