/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace P4API {

public enum ErrorFmtOps {
  EF_PLAIN = 0x00,
  EF_INDENT = 0x01,
  EF_NEWLINE = 0x02,
  EF_NOXLATE = 0x04
}

}
