/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace P4API {

using System;
using System.Runtime.InteropServices;

class p4apiPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [DllImport("p4api", EntryPoint="SWIGRegisterExceptionCallbacks_p4api")]
    public static extern void SWIGRegisterExceptionCallbacks_p4api(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [DllImport("p4api", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_p4api")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_p4api(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_p4api(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_p4api(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [ThreadStatic]
    private static Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(Exception e) {
      if (pendingException != null)
        throw new ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(p4apiPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static Exception Retrieve() {
      Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(p4apiPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("p4api", EntryPoint="SWIGRegisterStringCallback_p4api")]
    public static extern void SWIGRegisterStringCallback_p4api(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_p4api(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  [DllImport("p4api", EntryPoint="CSharp_ErrorId_code_set")]
  public static extern void ErrorId_code_set(HandleRef jarg1, int jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ErrorId_code_get")]
  public static extern int ErrorId_code_get(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ErrorId_fmt_set")]
  public static extern void ErrorId_fmt_set(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ErrorId_fmt_get")]
  public static extern string ErrorId_fmt_get(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ErrorId_SubCode")]
  public static extern int ErrorId_SubCode(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ErrorId_Subsystem")]
  public static extern int ErrorId_Subsystem(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ErrorId_Generic")]
  public static extern int ErrorId_Generic(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ErrorId_ArgCount")]
  public static extern int ErrorId_ArgCount(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ErrorId_Severity")]
  public static extern int ErrorId_Severity(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ErrorId_UniqueCode")]
  public static extern int ErrorId_UniqueCode(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_ErrorId")]
  public static extern IntPtr new_ErrorId();

  [DllImport("p4api", EntryPoint="CSharp_delete_ErrorId")]
  public static extern void delete_ErrorId(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_Error")]
  public static extern IntPtr new_Error();

  [DllImport("p4api", EntryPoint="CSharp_delete_Error")]
  public static extern void delete_Error(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_Error_Clear")]
  public static extern void Error_Clear(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_Error_Test")]
  public static extern int Error_Test(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_Error_IsInfo")]
  public static extern int Error_IsInfo(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_Error_IsWarning")]
  public static extern int Error_IsWarning(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_Error_IsError")]
  public static extern int Error_IsError(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_Error_IsFatal")]
  public static extern int Error_IsFatal(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_Error_GetSeverity")]
  public static extern int Error_GetSeverity(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_Error_FmtSeverity")]
  public static extern string Error_FmtSeverity(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_Error_GetGeneric")]
  public static extern int Error_GetGeneric(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_Error_Set__SWIG_0")]
  public static extern IntPtr Error_Set__SWIG_0(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_Error_Set__SWIG_1")]
  public static extern IntPtr Error_Set__SWIG_1(HandleRef jarg1, int jarg2, string jarg3);

  [DllImport("p4api", EntryPoint="CSharp_Error_Sys")]
  public static extern void Error_Sys(HandleRef jarg1, string jarg2, string jarg3);

  [DllImport("p4api", EntryPoint="CSharp_Error_Net")]
  public static extern void Error_Net(HandleRef jarg1, string jarg2, string jarg3);

  [DllImport("p4api", EntryPoint="CSharp_Error_GetId")]
  public static extern IntPtr Error_GetId(HandleRef jarg1, int jarg2);

  [DllImport("p4api", EntryPoint="CSharp_Error_CheckId")]
  public static extern int Error_CheckId(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_Error_GetDict")]
  public static extern IntPtr Error_GetDict(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_Error_Fmt__SWIG_0")]
  public static extern void Error_Fmt__SWIG_0(HandleRef jarg1, HandleRef jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_Error_Fmt__SWIG_2")]
  public static extern void Error_Fmt__SWIG_2(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_Error_Marshall0")]
  public static extern void Error_Marshall0(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_Error_Marshall1")]
  public static extern void Error_Marshall1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_Error_Marshall2")]
  public static extern void Error_Marshall2(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_Error_UnMarshall0")]
  public static extern void Error_UnMarshall0(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_Error_UnMarshall1")]
  public static extern void Error_UnMarshall1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_Error_UnMarshall2")]
  public static extern void Error_UnMarshall2(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_Error_Snap")]
  public static extern void Error_Snap(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_Error_Dump")]
  public static extern void Error_Dump(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_Text")]
  public static extern string StrPtr_Text(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_Value")]
  public static extern string StrPtr_Value(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_Length")]
  public static extern int StrPtr_Length(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_End")]
  public static extern string StrPtr_End(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_Atoi__SWIG_0")]
  public static extern int StrPtr_Atoi__SWIG_0(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_Atoi64__SWIG_0")]
  public static extern IntPtr StrPtr_Atoi64__SWIG_0(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_SetLength__SWIG_0")]
  public static extern void StrPtr_SetLength__SWIG_0(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_SetLength__SWIG_1")]
  public static extern void StrPtr_SetLength__SWIG_1(HandleRef jarg1, int jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_SetEnd")]
  public static extern void StrPtr_SetEnd(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_Compare")]
  public static extern int StrPtr_Compare(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_CCompare__SWIG_0")]
  public static extern int StrPtr_CCompare__SWIG_0(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_SCompare__SWIG_0")]
  public static extern int StrPtr_SCompare__SWIG_0(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_CCompare__SWIG_1")]
  public static extern int StrPtr_CCompare__SWIG_1(string jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_SCompare__SWIG_1")]
  public static extern int StrPtr_SCompare__SWIG_1(string jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_SCompare__SWIG_2")]
  public static extern int StrPtr_SCompare__SWIG_2(byte jarg1, byte jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_SEqual")]
  public static extern int StrPtr_SEqual(byte jarg1, byte jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_SCompareN")]
  public static extern int StrPtr_SCompareN(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_XCompare__SWIG_0")]
  public static extern int StrPtr_XCompare__SWIG_0(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_XCompare__SWIG_1")]
  public static extern int StrPtr_XCompare__SWIG_1(string jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_XCompareN")]
  public static extern int StrPtr_XCompareN(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_Contains")]
  public static extern string StrPtr_Contains(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_StrCpy")]
  public static extern void StrPtr_StrCpy(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_StrCat")]
  public static extern void StrPtr_StrCat(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_Atoi__SWIG_1")]
  public static extern int StrPtr_Atoi__SWIG_1(string jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_Itoa")]
  public static extern string StrPtr_Itoa(int jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_Atoi64__SWIG_1")]
  public static extern IntPtr StrPtr_Atoi64__SWIG_1(string jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_Itoa64")]
  public static extern string StrPtr_Itoa64(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_CaseFolding")]
  public static extern int StrPtr_CaseFolding();

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_CaseIgnored")]
  public static extern int StrPtr_CaseIgnored();

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_CaseHybrid")]
  public static extern int StrPtr_CaseHybrid();

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_SetCaseFolding")]
  public static extern void StrPtr_SetCaseFolding(int jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrPtr_CaseUsage")]
  public static extern int StrPtr_CaseUsage();

  [DllImport("p4api", EntryPoint="CSharp_new_StrPtr")]
  public static extern IntPtr new_StrPtr();

  [DllImport("p4api", EntryPoint="CSharp_delete_StrPtr")]
  public static extern void delete_StrPtr(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_StrRef__SWIG_0")]
  public static extern IntPtr new_StrRef__SWIG_0();

  [DllImport("p4api", EntryPoint="CSharp_new_StrRef__SWIG_1")]
  public static extern IntPtr new_StrRef__SWIG_1(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_StrRef__SWIG_2")]
  public static extern IntPtr new_StrRef__SWIG_2(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_StrRef__SWIG_3")]
  public static extern IntPtr new_StrRef__SWIG_3(string jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_StrRef__SWIG_4")]
  public static extern IntPtr new_StrRef__SWIG_4(string jarg1, int jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrRef_Null")]
  public static extern IntPtr StrRef_Null();

  [DllImport("p4api", EntryPoint="CSharp_StrRef_Set__SWIG_0")]
  public static extern void StrRef_Set__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrRef_Set__SWIG_1")]
  public static extern void StrRef_Set__SWIG_1(HandleRef jarg1, string jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_StrRef_Set__SWIG_2")]
  public static extern void StrRef_Set__SWIG_2(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_delete_StrRef")]
  public static extern void delete_StrRef(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_StrBuf__SWIG_0")]
  public static extern IntPtr new_StrBuf__SWIG_0();

  [DllImport("p4api", EntryPoint="CSharp_StrBuf_StringInit")]
  public static extern void StrBuf_StringInit(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_delete_StrBuf")]
  public static extern void delete_StrBuf(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_StrBuf__SWIG_1")]
  public static extern IntPtr new_StrBuf__SWIG_1(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_StrBuf__SWIG_2")]
  public static extern IntPtr new_StrBuf__SWIG_2(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_StrBuf__SWIG_3")]
  public static extern IntPtr new_StrBuf__SWIG_3(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_StrBuf__SWIG_4")]
  public static extern IntPtr new_StrBuf__SWIG_4(string jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrBuf_Clear")]
  public static extern void StrBuf_Clear(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrBuf_Set__SWIG_0")]
  public static extern void StrBuf_Set__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrBuf_Set__SWIG_1")]
  public static extern void StrBuf_Set__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrBuf_Set__SWIG_3")]
  public static extern void StrBuf_Set__SWIG_3(HandleRef jarg1, string jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_StrBuf_Extend__SWIG_0")]
  public static extern void StrBuf_Extend__SWIG_0(HandleRef jarg1, string jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_StrBuf_Extend__SWIG_1")]
  public static extern void StrBuf_Extend__SWIG_1(HandleRef jarg1, char jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrBuf_Terminate")]
  public static extern void StrBuf_Terminate(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrBuf_Append__SWIG_0")]
  public static extern void StrBuf_Append__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrBuf_Append__SWIG_1")]
  public static extern void StrBuf_Append__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrBuf_Append__SWIG_2")]
  public static extern void StrBuf_Append__SWIG_2(HandleRef jarg1, string jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_StrBuf_Alloc")]
  public static extern string StrBuf_Alloc(HandleRef jarg1, int jarg2);

  [DllImport("p4api", EntryPoint="CSharp_new_StrNum__SWIG_0")]
  public static extern IntPtr new_StrNum__SWIG_0();

  [DllImport("p4api", EntryPoint="CSharp_new_StrNum__SWIG_1")]
  public static extern IntPtr new_StrNum__SWIG_1(int jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_StrNum__SWIG_2")]
  public static extern IntPtr new_StrNum__SWIG_2(int jarg1, int jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrNum_Set")]
  public static extern void StrNum_Set(HandleRef jarg1, int jarg2);

  [DllImport("p4api", EntryPoint="CSharp_delete_StrNum")]
  public static extern void delete_StrNum(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_StrVarName__SWIG_0")]
  public static extern IntPtr new_StrVarName__SWIG_0(string jarg1, int jarg2);

  [DllImport("p4api", EntryPoint="CSharp_new_StrVarName__SWIG_1")]
  public static extern IntPtr new_StrVarName__SWIG_1(HandleRef jarg1, int jarg2);

  [DllImport("p4api", EntryPoint="CSharp_new_StrVarName__SWIG_2")]
  public static extern IntPtr new_StrVarName__SWIG_2(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_delete_StrVarName")]
  public static extern void delete_StrVarName(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_delete_StrDict")]
  public static extern void delete_StrDict(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_CopyVars")]
  public static extern void StrDict_CopyVars(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_SetVar__SWIG_0")]
  public static extern void StrDict_SetVar__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_SetVar__SWIG_1")]
  public static extern void StrDict_SetVar__SWIG_1(HandleRef jarg1, string jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_SetVar__SWIG_2")]
  public static extern void StrDict_SetVar__SWIG_2(HandleRef jarg1, string jarg2, string jarg3);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_SetVar__SWIG_3")]
  public static extern void StrDict_SetVar__SWIG_3(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_SetVar__SWIG_5")]
  public static extern void StrDict_SetVar__SWIG_5(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_SetVarV")]
  public static extern void StrDict_SetVarV(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_SetArgv")]
  public static extern void StrDict_SetArgv(HandleRef jarg1, int argc, [MarshalAs(UnmanagedType.LPArray, ArraySubType=UnmanagedType.LPStr)] string[] jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_SetVar__SWIG_6")]
  public static extern void StrDict_SetVar__SWIG_6(HandleRef jarg1, HandleRef jarg2, int jarg3, HandleRef jarg4);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_SetVar__SWIG_7")]
  public static extern void StrDict_SetVar__SWIG_7(HandleRef jarg1, string jarg2, int jarg3, HandleRef jarg4);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_SetVar__SWIG_8")]
  public static extern void StrDict_SetVar__SWIG_8(HandleRef jarg1, string jarg2, int jarg3, int jarg4, HandleRef jarg5);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_GetVar__SWIG_0")]
  public static extern IntPtr StrDict_GetVar__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_GetVar__SWIG_1")]
  public static extern IntPtr StrDict_GetVar__SWIG_1(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_GetVar__SWIG_2")]
  public static extern IntPtr StrDict_GetVar__SWIG_2(HandleRef jarg1, HandleRef jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_GetVar__SWIG_3")]
  public static extern IntPtr StrDict_GetVar__SWIG_3(HandleRef jarg1, HandleRef jarg2, int jarg3, int jarg4);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_GetVar__SWIG_4")]
  public static extern IntPtr StrDict_GetVar__SWIG_4(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_GetVar__SWIG_5")]
  public static extern int StrDict_GetVar__SWIG_5(HandleRef jarg1, int jarg2, HandleRef jarg3, HandleRef jarg4);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_ReplaceVar")]
  public static extern void StrDict_ReplaceVar(HandleRef jarg1, string jarg2, string jarg3);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_RemoveVar")]
  public static extern void StrDict_RemoveVar(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_Clear")]
  public static extern void StrDict_Clear(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_Save")]
  public static extern int StrDict_Save(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrDict_Load")]
  public static extern int StrDict_Load(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_new_ClientUser")]
  public static extern IntPtr new_ClientUser();

  [DllImport("p4api", EntryPoint="CSharp_delete_ClientUser")]
  public static extern void delete_ClientUser(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_InputData")]
  public static extern void ClientUser_InputData(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_InputDataSwigExplicitClientUser")]
  public static extern void ClientUser_InputDataSwigExplicitClientUser(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_HandleError")]
  public static extern void ClientUser_HandleError(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_HandleErrorSwigExplicitClientUser")]
  public static extern void ClientUser_HandleErrorSwigExplicitClientUser(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_Message")]
  public static extern void ClientUser_Message(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_MessageSwigExplicitClientUser")]
  public static extern void ClientUser_MessageSwigExplicitClientUser(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputError")]
  public static extern void ClientUser_OutputError(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputErrorSwigExplicitClientUser")]
  public static extern void ClientUser_OutputErrorSwigExplicitClientUser(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputInfo")]
  public static extern void ClientUser_OutputInfo(HandleRef jarg1, char jarg2, string jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputInfoSwigExplicitClientUser")]
  public static extern void ClientUser_OutputInfoSwigExplicitClientUser(HandleRef jarg1, char jarg2, string jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputBinary")]
  public static unsafe extern void ClientUser_OutputBinary(HandleRef jarg1, sbyte * jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputBinarySwigExplicitClientUser")]
  public static unsafe extern void ClientUser_OutputBinarySwigExplicitClientUser(HandleRef jarg1, sbyte * jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputText")]
  public static unsafe extern void ClientUser_OutputText(HandleRef jarg1, sbyte * jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputTextSwigExplicitClientUser")]
  public static unsafe extern void ClientUser_OutputTextSwigExplicitClientUser(HandleRef jarg1, sbyte * jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputStat")]
  public static extern void ClientUser_OutputStat(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputStatSwigExplicitClientUser")]
  public static extern void ClientUser_OutputStatSwigExplicitClientUser(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_Prompt")]
  public static extern void ClientUser_Prompt(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, int jarg4, HandleRef jarg5);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_PromptSwigExplicitClientUser")]
  public static extern void ClientUser_PromptSwigExplicitClientUser(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, int jarg4, HandleRef jarg5);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_ErrorPause")]
  public static extern void ClientUser_ErrorPause(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_ErrorPauseSwigExplicitClientUser")]
  public static extern void ClientUser_ErrorPauseSwigExplicitClientUser(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_Edit__SWIG_0")]
  public static extern void ClientUser_Edit__SWIG_0(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_EditSwigExplicitClientUser__SWIG_0")]
  public static extern void ClientUser_EditSwigExplicitClientUser__SWIG_0(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_Diff")]
  public static extern void ClientUser_Diff(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, int jarg4, string jarg5, HandleRef jarg6);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_DiffSwigExplicitClientUser")]
  public static extern void ClientUser_DiffSwigExplicitClientUser(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, int jarg4, string jarg5, HandleRef jarg6);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_Merge")]
  public static extern void ClientUser_Merge(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, HandleRef jarg4, HandleRef jarg5, HandleRef jarg6);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_MergeSwigExplicitClientUser")]
  public static extern void ClientUser_MergeSwigExplicitClientUser(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3, HandleRef jarg4, HandleRef jarg5, HandleRef jarg6);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_Resolve")]
  public static extern int ClientUser_Resolve(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_ResolveSwigExplicitClientUser")]
  public static extern int ClientUser_ResolveSwigExplicitClientUser(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_Help")]
  public static extern void ClientUser_Help(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_HelpSwigExplicitClientUser")]
  public static extern void ClientUser_HelpSwigExplicitClientUser(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_File")]
  public static extern IntPtr ClientUser_File(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_FileSwigExplicitClientUser")]
  public static extern IntPtr ClientUser_FileSwigExplicitClientUser(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_Finished")]
  public static extern void ClientUser_Finished(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_FinishedSwigExplicitClientUser")]
  public static extern void ClientUser_FinishedSwigExplicitClientUser(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_varList_set")]
  public static extern void ClientUser_varList_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_varList_get")]
  public static extern IntPtr ClientUser_varList_get(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_enviro_set")]
  public static extern void ClientUser_enviro_set(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_enviro_get")]
  public static extern IntPtr ClientUser_enviro_get(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_Edit__SWIG_1")]
  public static extern void ClientUser_Edit__SWIG_1(HandleRef jarg1, HandleRef jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_RunCmd")]
  public static extern void ClientUser_RunCmd(string jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, string jarg7, HandleRef jarg8);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_SetOutputCharset")]
  public static extern void ClientUser_SetOutputCharset(HandleRef jarg1, int jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_SetOutputCharsetSwigExplicitClientUser")]
  public static extern void ClientUser_SetOutputCharsetSwigExplicitClientUser(HandleRef jarg1, int jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_DisableTmpCleanup")]
  public static extern void ClientUser_DisableTmpCleanup(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_DisableTmpCleanupSwigExplicitClientUser")]
  public static extern void ClientUser_DisableTmpCleanupSwigExplicitClientUser(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputError2")]
  public static extern int ClientUser_OutputError2(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputError2SwigExplicitClientUser")]
  public static extern int ClientUser_OutputError2SwigExplicitClientUser(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputInfo2")]
  public static extern int ClientUser_OutputInfo2(HandleRef jarg1, char jarg2, string jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_OutputInfo2SwigExplicitClientUser")]
  public static extern int ClientUser_OutputInfo2SwigExplicitClientUser(HandleRef jarg1, char jarg2, string jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_Help2")]
  public static extern int ClientUser_Help2(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_Help2SwigExplicitClientUser")]
  public static extern int ClientUser_Help2SwigExplicitClientUser(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientUser_director_connect")]
  public static extern void ClientUser_director_connect(HandleRef jarg1, ClientUser.SwigDelegateClientUser_0 delegate0, ClientUser.SwigDelegateClientUser_1 delegate1, ClientUser.SwigDelegateClientUser_2 delegate2, ClientUser.SwigDelegateClientUser_3 delegate3, ClientUser.SwigDelegateClientUser_4 delegate4, ClientUser.SwigDelegateClientUser_5 delegate5, ClientUser.SwigDelegateClientUser_6 delegate6, ClientUser.SwigDelegateClientUser_7 delegate7, ClientUser.SwigDelegateClientUser_8 delegate8, ClientUser.SwigDelegateClientUser_9 delegate9, ClientUser.SwigDelegateClientUser_10 delegate10, ClientUser.SwigDelegateClientUser_11 delegate11, ClientUser.SwigDelegateClientUser_12 delegate12, ClientUser.SwigDelegateClientUser_13 delegate13, ClientUser.SwigDelegateClientUser_14 delegate14, ClientUser.SwigDelegateClientUser_15 delegate15, ClientUser.SwigDelegateClientUser_16 delegate16, ClientUser.SwigDelegateClientUser_17 delegate17, ClientUser.SwigDelegateClientUser_18 delegate18, ClientUser.SwigDelegateClientUser_19 delegate19, ClientUser.SwigDelegateClientUser_20 delegate20, ClientUser.SwigDelegateClientUser_21 delegate21);

  [DllImport("p4api", EntryPoint="CSharp_new_ClientApi__SWIG_0")]
  public static extern IntPtr new_ClientApi__SWIG_0();

  [DllImport("p4api", EntryPoint="CSharp_delete_ClientApi")]
  public static extern void delete_ClientApi(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetTrans__SWIG_0")]
  public static extern void ClientApi_SetTrans__SWIG_0(HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetTrans__SWIG_1")]
  public static extern void ClientApi_SetTrans__SWIG_1(HandleRef jarg1, int jarg2, int jarg3, int jarg4);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetTrans__SWIG_2")]
  public static extern void ClientApi_SetTrans__SWIG_2(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetTrans__SWIG_3")]
  public static extern void ClientApi_SetTrans__SWIG_3(HandleRef jarg1, int jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetProtocol")]
  public static extern void ClientApi_SetProtocol(HandleRef jarg1, string jarg2, string jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetProtocolV")]
  public static extern void ClientApi_SetProtocolV(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_GetProtocol")]
  public static extern IntPtr ClientApi_GetProtocol(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_Init")]
  public static extern void ClientApi_Init(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_Run__SWIG_0")]
  public static extern void ClientApi_Run__SWIG_0(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_Final")]
  public static extern int ClientApi_Final(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_Dropped")]
  public static extern int ClientApi_Dropped(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_GetErrors")]
  public static extern int ClientApi_GetErrors(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_RunTag")]
  public static extern void ClientApi_RunTag(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_WaitTag__SWIG_0")]
  public static extern void ClientApi_WaitTag__SWIG_0(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_WaitTag__SWIG_1")]
  public static extern void ClientApi_WaitTag__SWIG_1(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetCharset__SWIG_0")]
  public static extern void ClientApi_SetCharset__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetClient__SWIG_0")]
  public static extern void ClientApi_SetClient__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetCwd__SWIG_0")]
  public static extern void ClientApi_SetCwd__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetHost__SWIG_0")]
  public static extern void ClientApi_SetHost__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetLanguage__SWIG_0")]
  public static extern void ClientApi_SetLanguage__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetPassword__SWIG_0")]
  public static extern void ClientApi_SetPassword__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetPort__SWIG_0")]
  public static extern void ClientApi_SetPort__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetUser__SWIG_0")]
  public static extern void ClientApi_SetUser__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetProg__SWIG_0")]
  public static extern void ClientApi_SetProg__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetVersion__SWIG_0")]
  public static extern void ClientApi_SetVersion__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetTicketFile__SWIG_0")]
  public static extern void ClientApi_SetTicketFile__SWIG_0(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetCharset__SWIG_1")]
  public static extern void ClientApi_SetCharset__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetClient__SWIG_1")]
  public static extern void ClientApi_SetClient__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetCwd__SWIG_1")]
  public static extern void ClientApi_SetCwd__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetHost__SWIG_1")]
  public static extern void ClientApi_SetHost__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetLanguage__SWIG_1")]
  public static extern void ClientApi_SetLanguage__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetPassword__SWIG_1")]
  public static extern void ClientApi_SetPassword__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetPort__SWIG_1")]
  public static extern void ClientApi_SetPort__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetUser__SWIG_1")]
  public static extern void ClientApi_SetUser__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetProg__SWIG_1")]
  public static extern void ClientApi_SetProg__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetVersion__SWIG_1")]
  public static extern void ClientApi_SetVersion__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetTicketFile__SWIG_1")]
  public static extern void ClientApi_SetTicketFile__SWIG_1(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetBreak")]
  public static extern void ClientApi_SetBreak(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_DefineCharset")]
  public static extern void ClientApi_DefineCharset(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_DefineClient")]
  public static extern void ClientApi_DefineClient(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_DefineHost")]
  public static extern void ClientApi_DefineHost(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_DefineLanguage")]
  public static extern void ClientApi_DefineLanguage(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_DefinePassword")]
  public static extern void ClientApi_DefinePassword(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_DefinePort")]
  public static extern void ClientApi_DefinePort(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_DefineUser")]
  public static extern void ClientApi_DefineUser(HandleRef jarg1, string jarg2, HandleRef jarg3);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_GetCharset")]
  public static extern IntPtr ClientApi_GetCharset(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_GetClient")]
  public static extern IntPtr ClientApi_GetClient(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_GetCwd")]
  public static extern IntPtr ClientApi_GetCwd(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_GetHost")]
  public static extern IntPtr ClientApi_GetHost(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_GetLanguage")]
  public static extern IntPtr ClientApi_GetLanguage(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_GetOs")]
  public static extern IntPtr ClientApi_GetOs(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_GetPassword")]
  public static extern IntPtr ClientApi_GetPassword(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_GetPort")]
  public static extern IntPtr ClientApi_GetPort(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_GetUser")]
  public static extern IntPtr ClientApi_GetUser(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_GetConfig")]
  public static extern IntPtr ClientApi_GetConfig(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetIgnorePassword")]
  public static extern void ClientApi_SetIgnorePassword(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_new_ClientApi__SWIG_1")]
  public static extern IntPtr new_ClientApi__SWIG_1(HandleRef jarg1);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_SetUi")]
  public static extern void ClientApi_SetUi(HandleRef jarg1, HandleRef jarg2);

  [DllImport("p4api", EntryPoint="CSharp_ClientApi_Run__SWIG_1")]
  public static extern void ClientApi_Run__SWIG_1(HandleRef jarg1, string jarg2);

  [DllImport("p4api", EntryPoint="CSharp_StrRefUpcast")]
  public static extern IntPtr StrRefUpcast(IntPtr objectRef);

  [DllImport("p4api", EntryPoint="CSharp_StrBufUpcast")]
  public static extern IntPtr StrBufUpcast(IntPtr objectRef);

  [DllImport("p4api", EntryPoint="CSharp_StrNumUpcast")]
  public static extern IntPtr StrNumUpcast(IntPtr objectRef);

  [DllImport("p4api", EntryPoint="CSharp_StrVarNameUpcast")]
  public static extern IntPtr StrVarNameUpcast(IntPtr objectRef);

  [DllImport("p4api", EntryPoint="CSharp_ClientApiUpcast")]
  public static extern IntPtr ClientApiUpcast(IntPtr objectRef);
}

}
