/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace P4API {

using System;
using System.Runtime.InteropServices;

public class StrDict : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal StrDict(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(StrDict obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~StrDict() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        p4apiPINVOKE.delete_StrDict(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public void CopyVars(StrDict other) {
    p4apiPINVOKE.StrDict_CopyVars(swigCPtr, StrDict.getCPtr(other));
    if (p4apiPINVOKE.SWIGPendingException.Pending) throw p4apiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetVar(string var) {
    p4apiPINVOKE.StrDict_SetVar__SWIG_0(swigCPtr, var);
  }

  public void SetVar(string var, int value) {
    p4apiPINVOKE.StrDict_SetVar__SWIG_1(swigCPtr, var, value);
  }

  public void SetVar(string var, string value) {
    p4apiPINVOKE.StrDict_SetVar__SWIG_2(swigCPtr, var, value);
  }

  public void SetVar(string var, StrPtr value) {
    p4apiPINVOKE.StrDict_SetVar__SWIG_3(swigCPtr, var, StrPtr.getCPtr(value));
  }

  public void SetVar(StrPtr var, StrPtr value) {
    p4apiPINVOKE.StrDict_SetVar__SWIG_5(swigCPtr, StrPtr.getCPtr(var), StrPtr.getCPtr(value));
    if (p4apiPINVOKE.SWIGPendingException.Pending) throw p4apiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetVarV(string arg) {
    p4apiPINVOKE.StrDict_SetVarV(swigCPtr, arg);
  }

  public void SetArgv(string[] argc) {
    p4apiPINVOKE.StrDict_SetArgv(swigCPtr, argc.Length, argc);
  }

  public void SetVar(StrPtr var, int x, StrPtr val) {
    p4apiPINVOKE.StrDict_SetVar__SWIG_6(swigCPtr, StrPtr.getCPtr(var), x, StrPtr.getCPtr(val));
    if (p4apiPINVOKE.SWIGPendingException.Pending) throw p4apiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetVar(string var, int x, StrPtr val) {
    p4apiPINVOKE.StrDict_SetVar__SWIG_7(swigCPtr, var, x, StrPtr.getCPtr(val));
    if (p4apiPINVOKE.SWIGPendingException.Pending) throw p4apiPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetVar(string var, int x, int y, StrPtr val) {
    p4apiPINVOKE.StrDict_SetVar__SWIG_8(swigCPtr, var, x, y, StrPtr.getCPtr(val));
    if (p4apiPINVOKE.SWIGPendingException.Pending) throw p4apiPINVOKE.SWIGPendingException.Retrieve();
  }

  public StrPtr GetVar(string var) {
    IntPtr cPtr = p4apiPINVOKE.StrDict_GetVar__SWIG_0(swigCPtr, var);
    StrPtr ret = (cPtr == IntPtr.Zero) ? null : new StrPtr(cPtr, false);
    return ret;
  }

  public StrPtr GetVar(string var, Error e) {
    IntPtr cPtr = p4apiPINVOKE.StrDict_GetVar__SWIG_1(swigCPtr, var, Error.getCPtr(e));
    StrPtr ret = (cPtr == IntPtr.Zero) ? null : new StrPtr(cPtr, false);
    return ret;
  }

  public StrPtr GetVar(StrPtr var, int x) {
    IntPtr cPtr = p4apiPINVOKE.StrDict_GetVar__SWIG_2(swigCPtr, StrPtr.getCPtr(var), x);
    StrPtr ret = (cPtr == IntPtr.Zero) ? null : new StrPtr(cPtr, false);
    if (p4apiPINVOKE.SWIGPendingException.Pending) throw p4apiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public StrPtr GetVar(StrPtr var, int x, int y) {
    IntPtr cPtr = p4apiPINVOKE.StrDict_GetVar__SWIG_3(swigCPtr, StrPtr.getCPtr(var), x, y);
    StrPtr ret = (cPtr == IntPtr.Zero) ? null : new StrPtr(cPtr, false);
    if (p4apiPINVOKE.SWIGPendingException.Pending) throw p4apiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public StrPtr GetVar(StrPtr var) {
    IntPtr cPtr = p4apiPINVOKE.StrDict_GetVar__SWIG_4(swigCPtr, StrPtr.getCPtr(var));
    StrPtr ret = (cPtr == IntPtr.Zero) ? null : new StrPtr(cPtr, false);
    if (p4apiPINVOKE.SWIGPendingException.Pending) throw p4apiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetVar(int x, StrRef var, StrRef val) {
    int ret = p4apiPINVOKE.StrDict_GetVar__SWIG_5(swigCPtr, x, StrRef.getCPtr(var), StrRef.getCPtr(val));
    if (p4apiPINVOKE.SWIGPendingException.Pending) throw p4apiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ReplaceVar(string var, string value) {
    p4apiPINVOKE.StrDict_ReplaceVar(swigCPtr, var, value);
  }

  public void RemoveVar(string var) {
    p4apiPINVOKE.StrDict_RemoveVar(swigCPtr, var);
  }

  public void Clear() {
    p4apiPINVOKE.StrDict_Clear(swigCPtr);
  }

  public int Save(SWIGTYPE_p_FILE arg0) {
    int ret = p4apiPINVOKE.StrDict_Save(swigCPtr, SWIGTYPE_p_FILE.getCPtr(arg0));
    return ret;
  }

  public int Load(SWIGTYPE_p_FILE arg0) {
    int ret = p4apiPINVOKE.StrDict_Load(swigCPtr, SWIGTYPE_p_FILE.getCPtr(arg0));
    return ret;
  }

}

}
