/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.33
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace P4API {

using System;
using System.Runtime.InteropServices;

public class StrRef : StrPtr {
  private HandleRef swigCPtr;

  internal StrRef(IntPtr cPtr, bool cMemoryOwn) : base(p4apiPINVOKE.StrRefUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(StrRef obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~StrRef() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        p4apiPINVOKE.delete_StrRef(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public StrRef() : this(p4apiPINVOKE.new_StrRef__SWIG_0(), true) {
  }

  public StrRef(StrRef s) : this(p4apiPINVOKE.new_StrRef__SWIG_1(StrRef.getCPtr(s)), true) {
    if (p4apiPINVOKE.SWIGPendingException.Pending) throw p4apiPINVOKE.SWIGPendingException.Retrieve();
  }

  public StrRef(StrPtr s) : this(p4apiPINVOKE.new_StrRef__SWIG_2(StrPtr.getCPtr(s)), true) {
    if (p4apiPINVOKE.SWIGPendingException.Pending) throw p4apiPINVOKE.SWIGPendingException.Retrieve();
  }

  public StrRef(string buf) : this(p4apiPINVOKE.new_StrRef__SWIG_3(buf), true) {
  }

  public StrRef(string buf, int len) : this(p4apiPINVOKE.new_StrRef__SWIG_4(buf, len), true) {
  }

  public static StrPtr Null() {
    StrPtr ret = new StrPtr(p4apiPINVOKE.StrRef_Null(), false);
    return ret;
  }

  public void Set(string buf) {
    p4apiPINVOKE.StrRef_Set__SWIG_0(swigCPtr, buf);
  }

  public void Set(string buf, int len) {
    p4apiPINVOKE.StrRef_Set__SWIG_1(swigCPtr, buf, len);
  }

  public void Set(StrPtr s) {
    p4apiPINVOKE.StrRef_Set__SWIG_2(swigCPtr, StrPtr.getCPtr(s));
  }

}

}
